### ISSUE TITLE
Infinite redirect loop when using robots.txt

### ISSUE THREAD

**Issue by emirkin** [sparklemotion/mechanize#240]
I get into an infinite loop of redirects when trying to access http://zynga.com

```
agent = Mechanize.new
agent.follow_meta_refresh = true
agent.robots = true
agent.get http://zynga.com # <-- hangs
```

If I interrupt last command, I get this stacktrace (with ever-increasing levels of depth depending on how long I wait):

```
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:258:in `fetch'
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:955:in `get_robots'
... 251 levels...
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:949:in `response_redirect'
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:299:in `fetch'
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:955:in `get_robots'
    from .rvm/gems/ruby-1.9.3-p125/gems/webrobots-0.0.13/lib/webrobots.rb:135:in `call'
    from .rvm/gems/ruby-1.9.3-p125/gems/webrobots-0.0.13/lib/webrobots.rb:135:in `fetch_robots_txt'
    from .rvm/gems/ruby-1.9.3-p125/gems/webrobots-0.0.13/lib/webrobots.rb:130:in `get_robots_txt'
    from .rvm/gems/ruby-1.9.3-p125/gems/webrobots-0.0.13/lib/webrobots.rb:51:in `allowed?'
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:974:in `robots_allowed?'
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize/http/agent.rb:238:in `fetch'
    from .rvm/gems/ruby-1.9.3-p125/gems/mechanize-2.5.1/lib/mechanize.rb:407:in `get
```

Here's what Mechanize's log shows (listing only the relevant part):

```

Net::HTTP::Get: /robots.txt
status: Net::HTTPMovedPermanently 1.1 301 Moved Permanently
follow redirect to: https://zynga.com/robots.txt

Net::HTTP::Get: /robots.txt
status: Net::HTTPFound 1.1 302 Found
follow redirect to: https://zynga.com/#/robots.txt

Net::HTTP::Get: /robots.txt
status: Net::HTTPFound 1.1 302 Found
follow redirect to: https://zynga.com/#/robots.txt

Net::HTTP::Get: /robots.txt
status: Net::HTTPFound 1.1 302 Found
follow redirect to: https://zynga.com/#/robots.txt

...
```

Looking through the code, I see that there is some limit on redirects inside the agent code. It looks like there's a code branch that jumps over that check though.

**Comment by dwo** [comment]
I am actually seeing a `stack level too deep (SystemStackError)` when trying to fetch from a site which has 301-redirected its `robots.txt`.

I think what is happening is
* Try to download `/`
  * Download `robots.txt` to check if we can download `/`
  * 301 redirect, download `robots_foo.txt` instead
    * Download `robots.txt` to check if we can download `/robots_foo.txt`
    * 301 redirect, download `robots_foo.txt` instead
      * here we go again...

Perhaps https://github.com/sparklemotion/mechanize/blob/v2.7.3/lib/mechanize/http/agent.rb#L998-L1002 (or the `fetch` in `get_robots`?) needs some kind of short circuit to allow `robots.txt` to be somewhere other than `robots.txt`?
