### ISSUE TITLE
 SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 

### ISSUE THREAD

**Issue by paulschreiber** [sparklemotion/mechanize#265]
I am seeing this error intermittently:

```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

I do set the CA file:

```
Mechanize.new do |agent|
  agent.ssl_version = "SSLv3"
  agent.ca_file = Rails.root.join("lib/cacert.pem").to_s
end
```

I have also tried using `cert_store`:

```
cert_store = OpenSSL::X509::Store.new
cert_store.set_default_paths

Mechanize.new do |agent|
  agent.ssl_version = "SSLv3"
  agent.cert_store = cert_store
end
```

And setting the store explicitly:

```
cert_store = OpenSSL::X509::Store.new
cert_store.add_file Rails.root.join("lib/cacert.pem").to_s

Mechanize.new do |agent|
  agent.ssl_version = "SSLv3"
  agent.cert_store = cert_store
end
```

But these errors appear. When I run the code manually from rails console, it works fine. Which of the above, if any, are correct? What else can I do to debug this?

**Comment by mrinmayk** [comment]
hello drbrain,
what if the signature does not match any of the certificates?

**Comment by drbrain** [comment]
@mrinmayk then you need to find the CA Certificate (the certificate that signed the website's certificate) and add it to your trusted certificates list.
