### ISSUE TITLE
Undefined method 'path' for nil:NilClass 

### ISSUE THREAD

**Issue by guilhermediniz11** [sparklemotion/mechanize#385]
Does anyone know this error?? It occurs when i execute this script:

```
agent = Mechanize.new
agent.get("http://www.eumeinteresso.com.br/oferta-nacional/eletro-info/notebook-acer-aspire-i3-6gb-500gb-de-hd")
```

NoMethodError: undefined method `path' for nil:NilClass
    from /home/guilherme/.rvm/gems/ruby-2.1.1@omni-scraper/gems/mechanize-2.7.2/lib/mechanize/http/agent.rb:823:in`ensure in response_content_encoding'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@omni-scraper/gems/mechanize-2.7.2/lib/mechanize/http/agent.rb:821:in `response_content_encoding'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@omni-scraper/gems/mechanize-2.7.2/lib/mechanize/http/agent.rb:273:in`fetch'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@omni-scraper/gems/mechanize-2.7.2/lib/mechanize.rb:432:in `get'
    from (irb):23
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/cli/console.rb:38:in`run'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/cli.rb:287:in `console'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/command.rb:27:in`run'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/vendor/thor.rb:363:in`dispatch'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/vendor/thor/base.rb:440:in `start'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/cli.rb:9:in`start'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/bin/bundle:20:in `block in <top (required)>'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/lib/bundler/friendly_errors.rb:5:in`with_friendly_errors'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/gems/bundler-1.6.2/bin/bundle:20:in `<top (required)>'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/bin/bundle:23:in`load'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@global/bin/bundle:23:in `<main>'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@omni-scraper/bin/ruby_executable_hooks:15:in`eval'
    from /home/guilherme/.rvm/gems/ruby-2.1.1@omni-scraper/bin/ruby_executable_hooks:15:in `<main>'

**Comment by EvanTedesco** [comment]
agent.gzip_enabled = false  fixed the issue for mea as well.  When I was handling the path error I was getting content-encoding error.  agent.gzip_enabled = false seemed to fix both issues for me.

**Comment by reprah** [comment]
@leejarvis Is there anything I can do to fix this issue?

I ran into it using mechanize 2.7.5 while receiving a response where the `Content-Encoding` header was set to `identity`.

```ruby
m = Mechanize::Agent.new
url = "https://www.researchgate.net/profile/Takeshi_Imaoka/publication/264057005_Monotherapy_with_the_once_weekly_GLP-1_receptor_agonist_dulaglutide_for_12_weeks_in_Japanese_patients_with_type_2_diabetes_Dose-dependent_effects_on_glycaemic_control_in_a_randomised_Double-blind_Plac/links/5605111f08ae5e8e3f312896.pdf"

begin
  m.get(url)
rescue StandardError => exception
  puts exception.message # "unsupported content-encoding: identity"
end
```

Here's the stacktrace:

```
/Users/hhenn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:827:in `response_content_encoding'
/Users/hhenn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/http/agent.rb:290:in `fetch'
/Users/hhenn/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize.rb:464:in `get'
```

"identity" is a [valid value for the Content-Encoding header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding). I noticed it isn't a handled Content-Encoding value in the [response_content_encoding](https://github.com/sparklemotion/mechanize/blob/master/lib/mechanize/http/agent.rb#L819) method; is there a reason why?

Thanks for the work you do and let me know if I can help.
