### ISSUE TITLE
Mechanize module documentation page is blank

### ISSUE THREAD

**Issue by cheenu** [sparklemotion/mechanize#387]
Please see http://docs.seattlerb.org/mechanize/Mechanize.html

I just get a blank page as can be seen in the screenshot

![screen shot 2014-07-29 at 3 48 04 pm](https://cloud.githubusercontent.com/assets/153911/3733588/b2726682-1709-11e4-897d-640f0e8fd0f8.png)

**Comment by leejarvis** [comment]
@drbrain Can you regen these docs please? (Don't think I have access)

**Comment by drbrain** [comment]
Uh:

```
$ rake publish_docs
rake aborted!
Don't know how to build task 'publish_docs'
```

You removed hoe? 😢 No wonder you can't push documentation, all the automation is gone.

**Comment by leejarvis** [comment]
It went in #358

**Comment by drbrain** [comment]
Oh right: https://github.com/sparklemotion/mechanize/pull/358#issuecomment-35573199

I'll rebuild your publish_docs task.

**Comment by drbrain** [comment]
Task restored by @cd8c4461 and documentation is published.
