### ISSUE TITLE
Cannot coexist with savon due to conflict between ntlm-http and rubyntlm; hacked gem binary available

### ISSUE THREAD

**Issue by cielavenir** [sparklemotion/mechanize#407]
I have difficulty with installing both mechanize and httpi (sadly both are loaded via http/ntlm). So could you update ntlm support to rubyntlm?

**Comment by cielavenir** [comment]
So, this gem just drops ntlm-http dependency, so mechanize will crash if savon is not installed. Hence, cannot be merged to mainstream by any ways...

**Comment by cielavenir** [comment]
Though it can be said that mainstream should move to rubyntlm, which is frequently maintained.
Or... when the NTLM support will be dropped. I need **EITHER**.

**Comment by flavorjones** [comment]
The next version of Mechanize will depend on `rubyntlm` (likely 2.8.0).
