### ISSUE TITLE
Form Radio Button - Wrong One Sent On Submission

### ISSUE THREAD

**Issue by daBee** [sparklemotion/mechanize#409]
It seems a radio button isn't taking after being set.  The server is saying I sent the button sent to another value.

The form:
  [radiobutton:0x3ff4bd04b428 type: radio name: searchCriteriaBean.conceptOperator value: and]
  [radiobutton:0x3ff4bd0322e8 type: radio name: searchCriteriaBean.conceptOperator value: accrue]
  [radiobutton:0x3ff4bd022924 type: radio name: searchCriteriaBean.conceptOperator value: ]
(last value should have a value of "phrase" but it is not showing up.  

My set:
searchCriteriaBean.conceptOperator - accrue

Result: 
Notifies me it was sent as "and"

Another issue.  In the original form inspection, It shows a nondescript field type that shows what I've set the field to use as a value:    [field:0x3fe009c36f1c type:  name: searchCriteriaBean.conceptOperator value: accrue]

Any further information needed, please let me know.  

Cheers

**Comment by daBee** [comment]
this_search = "fish bucket" 
    this_province = "" 
    this_operator = "accrue"																# 'accrue' or 'and' 
    form_url = "http://example.com/cccSrch.do?lang=eng&prtl=1&tagid=&profileId=&rstBtn.x=" 
     
    agent = Mechanize.new 
    page = agent.get(form_url) 
    CCCform = page.forms[0] 
    CCCform['searchPage'] = 'cccSrch.do?lang=eng&prtl=1&tagid=&profileId=&rstBtn.x=' 
    CCCform['searchCriteriaBean.textField'] = this_search 
    CCCform['searchCriteriaBean.conceptOperator'] = this_operator 
    CCCform['sbmtBtn'] = 'Search' 
    CCCform['searchCriteriaBean.column'] = '' 
    page2 = agent.submit(CCCform) 
     
    myform = CCCform.inspect 
    puts myform 
     
    counter = 0 
    CCCform.keys.each do |i| 
    	print "#{i} - " 
    	puts CCCform.values[counter] 
    	counter += 1 
    end 

searchCriteriaBean.conceptOperator is a radio button.

**Comment by leejarvis** [comment]
Closing this. Resolved on IRC

**Comment by muescha** [comment]
how was the solution?

**Comment by daBee** [comment]
You have to traverse the form in its GUI format and “check” id’s for radiobuttons.  As for checkboxes, same thing, but they remain sticky for the whole nameset.  

> On Jan 23, 2015, at 1:09 PM, muescha <notifications@github.com> wrote:
> 
> how was the solution?



beerich@gmail.com
