### ISSUE TITLE
cannot read unnamed form objects

### ISSUE THREAD

**Issue by pvl7** [sparklemotion/mechanize#410]
Hello

I have the following html page:

```html
<html>
<body>

<form name="testForm" action="/script">

<input name="named" value="value1" type="hidden">
<input id="unnamed" value="value2" type="hidden">

</form>

</body>
</html>
```

and try to read it with Mechanize:

```
> ruby testfetch.rb

#<Mechanize::Page
 {url #<URI::HTTP:0x000000025f66d8 URL:http://localhost/formtest.html>}
 {meta_refresh}
 {title nil}
 {iframes}
 {frames}
 {links}
 {forms
  #<Mechanize::Form
   {name "testForm"}
   {method "GET"}
   {action "/script"}
   {fields [hidden:0x1307a68 type: hidden name: named value: value1]}
   {radiobuttons}
   {checkboxes}
   {file_uploads}
   {buttons}>}>
```

```ruby
agent = Mechanize.new()
agent.log = Logger.new("mech.log")
agent.user_agent_alias = 'Mac FireFox'
login_page = agent.get('http://localhost/formtest.html')
p login_page
exit
```

and there is no the <input> object with the *id=* attribute which has no the *name=* attribute.

Is that a bug or I overlooked something?

Thanks!

**Comment by leejarvis** [comment]
These inputs are not important to Mechanize. [The specification](http://www.w3.org/TR/html401/interact/forms.html#successful-controls) mandates that only input elements with a `name` attribute are valid.

Therefore, Mechanize actively ignores input elements that do not have this attribute.
