### ISSUE TITLE
If multiple submit buttons are present on a form, all of them are included in the query

### ISSUE THREAD

**Issue by weshatheleopard** [sparklemotion/mechanize#416]
The following line ( https://github.com/sparklemotion/mechanize/blob/master/lib/mechanize/form.rb#L259 ) should NOT include `+ submits` — otherwise, if the form has multiple submit buttons:

```
<input type="submit" value="Delete">
<input type="submit" value="Next">
```

then the query string will include both, whereas they are exclusive — after all, you can't click both at once with a mouse.

**Comment by flavorjones** [comment]
This was reverted in d0cbc8f in July 2015 after a conversation in 1b55be172f88d5ba88795282c74dd2f0fbecda90
