### ISSUE TITLE
Parser halt when there is a NUL char in the parsed string

### ISSUE THREAD

**Issue by juliennicolas** [sparklemotion/mechanize#419]
If you crawl a webpage with a nul char inside the nokogiri parser will halt when reading it.
Maybe mechanize should handle this.

It's a way for somebody who don't want to be crawled to block you.

 https://github.com/sparklemotion/nokogiri/issues/1240

**Comment by leejarvis** [comment]
As you can see from the Nokogiri thread, it's related to libxml so nothing we can do here.
