### ISSUE TITLE
How to use TOR using mechanize ?

### ISSUE THREAD

**Issue by itshakeel23** [sparklemotion/mechanize#422]
I want to use SOCK based proxy using mechanize e.g TOR. 

e.g
agent = Mechanize.new
agent.set_proxy('127.0.0.1', '9050') #here how can i specify SOCK type ?
page = agent.get("http://google.com")

**Comment by sevk** [comment]
I also need socket5 proxy , thanks .

**Comment by drbrain** [comment]
Mechanize only supports HTTP proxies.  Maybe a tool like [torsocks](https://github.com/dgoulet/torsocks/) will help.
