### ISSUE TITLE
Page not parsing

### ISSUE THREAD

**Issue by dwkns** [sparklemotion/mechanize#423]
For some reason the following is not parsing

    require 'mechanize'
    agent = Mechanize.new
    page = agent.get('https://publisher.affili.net/Login/NewLogin.aspx')
    pp page

it outputs :

    #<Mechanize::Page
     {url #<URI::HTTPS https://publisher.affili.net/Login/NewLogin.aspx>}
     {meta_refresh}
     {title nil}
     {iframes}
     {frames}
     {links}
     {forms}>

However this :

    require 'mechanize'
    agent = Mechanize.new
    page = agent.get('http://google.com')
    pp page

gives as expected :

    #<Mechanize::Page
     {url
     #<URI::HTTP http://www.google.co.uk/?gfe_rd=cr&ei=SzfuVPXbPPGq8wfAtYHoBQ>}
     {meta_refresh}
     {title "Google"}
     {iframes}
     {frames}
     {links
     #<Mechanize::Page::Link
     "Images"
     "http://www.google.co.uk/imghp?hl=en&tab=wi">
     #<Mechanize::Page::Link "Maps" "http://maps.google.co.uk/maps?hl=en&tab=wl">
     ...
     {buttons
     [submit:0x3ff93e8e7d40 type: submit name: btnG value: Google Search]
     [submit:0x3ff93e8e7aac type: submit name: btnI value: I'm Feeling Lucky]}>}>

Now I know that the mark-up on [https://publisher.affili.net/Login/NewLogin.aspx](https://publisher.affili.net/Login/NewLogin.aspx)  is a whopping crock of kangaroo do do, but I would have expected at least to have gotten some information back. Especially the page title. Any ideas?

**Comment by leejarvis** [comment]
That's odd. Looks like `page.content_type` returns `"text/html; charset=UNICODE-1-1"` which seems incorrect.

For now, you can force the page encoding like so:

```ruby
agent = Mechanize.new
page = agent.get('https://publisher.affili.net/Login/NewLogin.aspx')
page.encoding = 'utf-8'

pp page
```

**Comment by leejarvis** [comment]
Right, it's not odd; the page explicitly sets `<meta http-equiv="content-type" content="text/html; charset=UNICODE-1-1" />`

**Comment by dwkns** [comment]
Works for me. Thanks.
