### ISSUE TITLE
Handling of Internationalized domains (IDNA)

### ISSUE THREAD

**Issue by NielsKSchjoedt** [sparklemotion/mechanize#430]
I'm trying to access some internationalized domains (e.g. http://www.nykøbing-autocenter.dk/) with mechanize. However the only thing I get is:

```
SocketError: getaddrinfo: nodename nor servname provided, or not known
from /Users/NK/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
```

What should I do about it?

**Comment by NielsKSchjoedt** [comment]
I solved it:

```
gem install simpleidn
```
and

```ruby
require ’simpleidn'
require 'mechanize'

a=SimpleIDN.to_ascii("nykøbing-autocenter.dk")
m=Mechanize.new
m.get('http://www.'+a)
```

**Comment by knu** [comment]
Thanks for the report.  Mechanize currently does not support IDNA.  It has to introduce a URL normalizer that converts IRI into ASCII-only URI, or links using Unicode IDN do not work.

While I consider Mechanize should fully support IDNA, I'm yet to decide if we should just implement a lax normalizer that just works for most cases, or properly implement (or make use of one of those implementations of) the latest [URL Standard](https://url.spec.whatwg.org/).  Give me awhile to think about it.

**Comment by knu** [comment]
By the way, Mechanize already depends on a library called `domain_name` that can deal with IDNA.  I haven't looked into `simpleidn` closely, but DomainName can do ToAscii conversion like this: `DomainName.normalize("nykøbing-autocenter.dk")`

**Comment by drbrain** [comment]
Ideally Net::HTTP would and/or URI would handle IDN for mechanize, but in the mean time we'll need to deal with it.

**Comment by NielsKSchjoedt** [comment]
Thanks. This makes a lot of sense.
