### ISSUE TITLE
How to deal with Cloudflare DDOS protection?

### ISSUE THREAD

**Issue by phuongnd08** [sparklemotion/mechanize#432]
When DDOS protection is on, Cloudflare return a 503 error page contains a script that will set a cookie and reload the page after 5 seconds. Could mechanize be modified to deal with that?

**Comment by leejarvis** [comment]
You'll have to handle this yourself. You can read the cookie and modify your program to deal with the new request. It's not something Mechanize does, or will, handle out of the box.
