### ISSUE TITLE
Upgrade Nokogiri Dependencies

### ISSUE THREAD

**Issue by GaryCarneiro** [sparklemotion/mechanize#433]
Hi,
The  Nokogiri dependencies still point to 1.4. and current stable is ~> 1.6
Can we please upgrade it to Nokogiri stable  and upload the gem ?

-Gary

**Comment by gchan** [comment]
It appears to have been updated in the gemspec to ~> 1.6 for nokogiri on the master branch. However this version has not been published to RubyGems.

**Comment by GaryCarneiro** [comment]
Ok.

**Comment by knu** [comment]
What's the problem with ~>1.4, anyway?

**Comment by GaryCarneiro** [comment]
@knu 

There was no problem from Ruby's perspective. Would work great from Gem File.
But I was making RPMs using (FPM)[https://github.com/jordansissel/fpm] which gave dependency error.

**Comment by knu** [comment]
Updating "~>1.4" with "~>1.6" simply makes the version requirement stricter, so I don't really see how it solves dependency error.  "~>1.4" is equivalent to [">=1.4", "<2.0"] and "~>1.6" is equivalent to [">=1.6", "<2.0"].
