### ISSUE TITLE
Pick the correct form from Mechanize results via CSS selector

### ISSUE THREAD

**Issue by DEATHMETALGORE** [sparklemotion/mechanize#434]
So I use Mechanize to fetch a list of forms for a page. The form identification can vary for websites, so I need something more stable, such as a selector.

Is there a way I can use a simple CSS selector to pick the right form from a list of forms provided by Mechanize?

**Comment by leejarvis** [comment]
Have you tried [form_with](http://docs.seattlerb.org/mechanize/Mechanize/Page.html#method-i-form_with)?
