### ISSUE TITLE
What can I do with  Net::HTTP::Persistent::Error: too many connection resets 

### ISSUE THREAD

**Issue by xuxiangyang** [sparklemotion/mechanize#435]
Hi， I am getting the error Net::HTTP::Persistent::Error. there is lots of issue discussing about it, but none of them found a way to fix this error. Can you help me?

my ruby version is 2.0.0-p481
mechanize version is 2.7.2
net-http-persistent version  is 2.9.4

I use mechanize in production environment, this error occurs when the number of connections goes up.

Will it fix this error if I deploy to more computers. or use more proxies? 
Will if fix this error if I rescue this error, then retry after sleep a while?

I this this error may be the biggest problem of mechanize.
I need some help.
Thank you

**Comment by leejarvis** [comment]
There are lots of details for this issue in #123. In short, we don't have a quick-fix solution. If you're able to provide a reusable example please re-open that ticket with all of the relevant information. Thanks!
