### ISSUE TITLE
using mechanize and savon: ruby-ntlm clashes

### ISSUE THREAD

**Issue by zdavatz** [sparklemotion/mechanize#436]
Using mechanize and savon can lead to clashes of which version of ruby-ntml should be used. The issues is also reported here: 

https://github.com/WinRb/rubyntlm/issues/13

The problem is that savon and mechanize each use (by direct or indirect require) ruby-ntlm.

Depending whether we used bundle exec or an installed version of our gem (that uses savon) the order of includes seems to differ and used different version of rubyntlm.

We solved it like this:

https://github.com/zdavatz/oddb2xml/commit/79257135b89b30617970460d4ac3f5771fc26e31

**Comment by cielavenir** [comment]
My modified gemspec drops ntlm-http dependency (thus mechanize will crash if savon is not installed). lol...
https://github.com/sparklemotion/mechanize/issues/407

**Comment by lnussbaum** [comment]
Hi,

I think that, instead of using ntlm-http, mechanize should just use rubyntlm. ntlm-http actually bundles an old version of rubyntlm source code.

I could not find if mechanize used what is added by ntlm-http on top of standard ntlm, but at least it seems to work without any issue.

**Comment by zdavatz** [comment]
Thanks for posting!

**Comment by cielavenir** [comment]
Before closing, please update the gemspec... I have very bad difficulty using gem command. Actually I didn't want to close #407, but I was just sure my proposal would not be accepted (bah)

**Comment by flavorjones** [comment]
The next version of Mechanize will depend on `rubyntlm` (likely 2.8.0).
