### ISSUE TITLE
401 response cannot be processed as a page

### ISSUE THREAD

**Issue by nir0** [sparklemotion/mechanize#437]
login form is delivered with 401 status by a webserver, which results in error in mechanise. i still need to put login and password into form, how do i bypass this?

**Comment by leejarvis** [comment]
Maybe you need to add the credentials to the request if this is HTTP authentication. You can do that via `add_auth`: http://www.rubydoc.info/gems/mechanize/Mechanize%3Aadd_auth

In general though, you can catch the Mechanize exception and use the page object:

```ruby
m = Mechanize.new

begin
  page = m.get("...")
rescue Mechanize::Error => e
  # log error
  page = e.page
end
```
