### ISSUE TITLE
v2.7.3 failed with test_build_query_string_complex 

### ISSUE THREAD

**Issue by xuxiangyang** [sparklemotion/mechanize#438]
Hi， when I run the test, I get a fail at [test_mechanize_util:139](https://github.com/sparklemotion/mechanize/blob/master/test/test_mechanize_util.rb#L139)，

the input_params is 
```ruby
    input_params = {
      number: 7,
      name: "\u{6B66}\u{8005}",
      "ids[]" => [1, 3, 5, 7],
      words: ["Sing", "Now!"],
      params: { x: "50%", y: "100%", t: [80, 160] },
    }
```

however when run ```@MU.build_query_string(input_params)```

the params I got is

```{:x=>"50%", :y=>"100%", :t=>"160"}```

I think this maybe a bug. 

The last change was made by @knu in 62f337b0648b3a2bc5857b223b4570d708d7fc82

I need some help, thank you~~~

**Comment by knu** [comment]
Thanks for the report.  It's a shame I didn't notice the breakage and have left it broken for a long time.

**Comment by knu** [comment]
Oops, sorry for the force-push.
