### ISSUE TITLE
Building a query with no value in Mechanize::Form::Text causes 500 Internal Server Errors

### ISSUE THREAD

**Issue by uksa** [sparklemotion/mechanize#440]
I have an issue, which **could** be bespoke to the development project I'm working on. There is a form, which depending on the drop-downs chosen can cause, once displayed fields to no longer be required when sending the form POST request. At least this is how it works in the browser and the query string looks like **fieldValue=&nextField=X**. So it has an empty value, this causes the Server to eventually throw a 500 as it was unhappy about receiving the empty value.

In order to prevent empty values in the build_query, I've added a monkey patch to my fork...

### Before
````
def build_query(buttons = [])
 ...
  when Mechanize::Form::Field
      successful_controls << f
  end
 ...
end
````

### After
````
 when Mechanize::Form::Field
   if f.kind_of?(Mechanize::Form::Text)
     if f.value != ""
       successful_controls << f
     end
   else
       successful_controls << f
   end
 end
````

I'll look over the next few days at the current tests and if all the tests pass and I can recreate with a new test, I'll create a pull request.

**Comment by uksa** [comment]
Change link to my fork:
https://github.com/uksa/mechanize/commit/786117a7f780eaba09845c6c1738718309cc2e0f

**Comment by uksa** [comment]
As a side note, looking over RFCs re, the validity of having an empty value, I could not find any clear evidence to say if this is acceptable, which probable means it is...!

**Comment by xuxiangyang** [comment]
I think mechanize should add this feature，some server detect if params has the key to do something~~~~ mechanize is common  crawler ，I think you should custom mechanize to fit your situation

**Comment by uksa** [comment]
Yes it would seem that if this was apparent at the Server level, then being able to switch at the agent level would be the best place. 

Perhaps something like a boolean for switching it on or off and defaulting to the way it is now, which allows blank values.

**Comment by uksa** [comment]
I've added a pull request:
https://github.com/sparklemotion/mechanize/pull/443

**Comment by uksa** [comment]
Given this has been hanging around since Sep2016, and a pull request was created, seems no point in leaving this open.
