### ISSUE TITLE
Page#form_with crashes when using :search option

### ISSUE THREAD

**Issue by raphinesse** [sparklemotion/mechanize#444]
Having fetched a page into the variable `page`, the following error is thrown when trying to query forms in the page. The trace should have all other relevant information.

```
irb(main):019:0> page.form_with(:search => '.foo form')
NoMethodError: undefined method `node' for #<Mechanize::Form:0x3936ca8>
        from C:/Software/Ruby21/lib/ruby/gems/2.1.0/gems/mechanize-2.7.3/lib/mechanize/form.rb:217:in `method_missing'
        from (eval):40:in `block in select_forms'
        from (eval):39:in `each'
        from (eval):39:in `find_all'
        from (eval):39:in `select_forms'
        from (eval):12:in `forms_with'
        from (eval):22:in `form_with'
        from (irb):19
        from C:/Software/Ruby21/bin/irb:11:in `<main>'
```

For your convenience: [The crash location](https://github.com/sparklemotion/mechanize/blob/v2.7.3/lib/mechanize/element_matcher.rb#L44)

**Comment by xuxiangyang** [comment]
I think
you should read this [form_with criteria](https://github.com/sparklemotion/mechanize/blob/master/lib/mechanize/element_matcher.rb#L29)

search is not a method for form，you should use [form methods](https://github.com/sparklemotion/mechanize/blob/v2.7.3/lib/mechanize/form.rb) as search key

I hole that would be useful for you.

**Comment by raphinesse** [comment]
Please note that `:search`, `:css` and `:xpath` keys are treated specially. Also, note that the behavior expected by me is explicitly supported in the [documentation](http://docs.seattlerb.org/mechanize/Mechanize/Page.html#method-i-forms_with).

**Comment by xuxiangyang** [comment]
try to use xpath with search?

**Comment by raphinesse** [comment]
The latest release (2.7.3), which I used, only supports the `:search` key. The version supporting `:css` and `:xpath` keys is not yet released.

**Comment by steve0hh** [comment]
I am also having troubles doing the following too:

```
page.form_with(xpath: '//*[@id="login-form"]')
```

Also throws the error 

```
NoMethodError: undefined method `node' for #<Mechanize::Form:......
...
...
...
```

**Comment by Sathors** [comment]
I can confirm the problem @steve0hh is having.
```ruby
page.form_with css: '#my-id'
```
raises
```
/home/sathors/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mechanize-2.7.5/lib/mechanize/form.rb:217:in `method_missing': undefined method `node' for #<Mechanize::Form:0x005638282c6968> (NoMethodError)
        from (eval):51:in `block in select_forms'
        from (eval):50:in `each'
        from (eval):50:in `find_all'
        from (eval):50:in `select_forms'
        from (eval):23:in `forms_with'
        from (eval):33:in `form_with'
        from ./scraping.rb:19:in `<main>'
```

**Comment by knu** [comment]
Indeed, this feature has been on the documentation for a long time but has never worked for forms, form fields and frames.  They would work only for such elements as links and images, it seems.

The above PR should fix the problem, so please give it a try.

**Comment by Sathors** [comment]
It is indeed now working for me, using the "search" and the "css".

Thanks a lot!

**Comment by knu** [comment]
Thanks for the quick confirmation.  I'll add some more tests and merge it.
