### ISSUE TITLE
Release new version on rubygems

### ISSUE THREAD

**Issue by jschroeder9000** [sparklemotion/mechanize#447]
The last release to rubygems was almost two years ago (2.7.3 on November 14, 2013).  In the time since then there has been 90 commits that address the rubyforge shutdown, fix bugs, and add new features (I'm particularly keen on 58cfaeb).  There has been a couple version tags pushed to github, but they were not pushed to rubygems.

Please consider releasing a new version.

**Comment by swistaczek** [comment]
+1 @leejarvis

**Comment by leejarvis** [comment]
Sorry I've been super hectic moving house lately. Myself or @knu can hopefully do this some time this week

**Comment by knu** [comment]
@leejarvis I'm not listed as member of the owners of the gem, so please add me if you don't have the time.  Also, is it OK to leave the breakage with JRuby (and Rubinius), or should we fix that before rolling out a new release?

**Comment by leejarvis** [comment]
@knu Thanks, I've added you as an owner (sorry, I thought you were!). I think we should look into the JRuby (and rbx) breakage before rolling out, hopefully it's not a time consuming problem

**Comment by knu** [comment]
@leejarvis Thanks!  I'll look into the breakage hopefully tomorrow and prepare a release if the problem can be solved.

**Comment by weshatheleopard** [comment]
+1

**Comment by thbar** [comment]
Based on the [rubygem page](https://rubygems.org/gems/mechanize), it looks like 2.7.5 was released in 2016.

I suppose this means this issue can be closed?

**Comment by knu** [comment]
Thanks, closing this!
