### ISSUE TITLE
why Mechanize cookie save function does not save origin property

### ISSUE THREAD

**Issue by xuxiangyang** [sparklemotion/mechanize#448]
I have a question, why Mechanize does not save Origin property? And what properties  should be save with cookie? how can I find some standard about cookies persistent？ 

I need some help.
Thank you.

**Comment by southwolf** [comment]
In most cases you do not need 'origin' property. Name, value, domain, path, secure would be enough.
See
https://www.nczonline.net/blog/2009/05/05/http-cookies-explained/
http://curl.haxx.se/rfc/cookie_spec.html
http://tools.ietf.org/html/rfc2965

**Comment by southwolf** [comment]
Or Chinese documents if you prefer:
http://www.cnblogs.com/sunzhenchao/p/3897890.html

**Comment by knu** [comment]
Mechanize complies with [RFC 6265](https://tools.ietf.org/html/rfc6265), and for the "origin" attribute there is [an Internet draft](http://tools.ietf.org/html/draft-west-origin-cookies-01) but it is still in progress.
