### ISSUE TITLE
Testing Mechanize with Rspec

### ISSUE THREAD

**Issue by jkalef** [sparklemotion/mechanize#453]
Do you have any specific recommendations on how to create "mock" mechanize responses for RSPEC testing?

**Comment by leejarvis** [comment]
Check out Mechanize::TestCase - https://github.com/sparklemotion/mechanize/blob/master/lib/mechanize/test_case.rb

[This line](https://github.com/sparklemotion/mechanize/blob/master/lib/mechanize/test_case.rb#L68) shows how you create a `Mechanize::Page` from some arbitrary content.

Hope that helps

**Comment by jkalef** [comment]
Thanks for your help.  This is great!

Cheers,

Jared
