### ISSUE TITLE
Infinite loop with 301'd robots.txt

### ISSUE THREAD

**Issue by dwo** [sparklemotion/mechanize#457]
I commented on #240 but I think it'll get lost on a closed issue.

I saw a `stack level too deep (SystemStackError)` when trying to fetch from a site which has 301-redirected its `robots.txt`.

I think what is happening is...
* Try to download `/`
  * Download `robots.txt` to check if we can download `/`
  * 301 redirect, download `robots_foo.txt` instead
    * Download `robots.txt` to check if we can download `/robots_foo.txt`
    * 301 redirect, download `robots_foo.txt` instead
      * here we go again...

Perhaps https://github.com/sparklemotion/mechanize/blob/v2.7.3/lib/mechanize/http/agent.rb#L998-L1002 (or the `fetch` in `get_robots`?) needs some kind of short circuit to allow `robots.txt` to be somewhere other than `/robots.txt`?

**Comment by knu** [comment]
I'll fix this shortly, but I'm pondering how redirection should be handled when fetching robots.txt; is it OK if redirection is not followed if the original mechanize object does not have `redirect_ok` set to true?  Should the redirection settings be overridden while fetching robots.txt?

**Comment by knu** [comment]
Also, redirection to another origin may possibly be used as means of attack.  Since /robots.txt on the redirected site is not looked upon, a spam site owner could redirect a site's /robots.txt to some other site's robot-forbidden content to get robots to access it.  This may not be much of a concern, though.

**Comment by dwo** [comment]
It does feel kind of messy doesn't it? I have only come across one site doing this ever. 

At least the `stack level too deep` error should be avoidable in this unusual situation.

**Comment by dwo** [comment]
Thank you @knu :heart: :green_heart: :red_circle: :blue_heart: :sparkling_heart:
