### ISSUE TITLE
#<Net::HTTP::Persistent::Error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET)>

### ISSUE THREAD

**Issue by HimanthTag** [sparklemotion/mechanize#461]
I am trying to crawl one of the site for which i keep on getting the following error

Net::HTTP::Persistent::Error: too many connection resets (due to Connection reset by peer - Errno::ECONNRESET) after 0 requests on 52672100, last used 1453200951.8505864 seconds ago

As i check their robots.txt, it seems they allow scrapping, not sure what else could be the reason.

I would greatly appreciate if anyone can help me on this, thanks in advance.

**Comment by hubsmoke** [comment]
I also see this issue a lot. Been scratching my head about it for a while

**Comment by genesisgonza05** [comment]
Hi, I have this problem with an simple request in my production code, in local it's work ok, but in production enviroment not, can you help me? thanks.

```
      @agent = Mechanize.new
      @agent.log = Logger.new "mech.log"
      @agent.keep_alive = true
      page = @agent.get uri
      form_search = page.form_with(name: 'search')
      form_search = page.form_with(name: 'search')
      form_search.field_with(name: "test").value = "search"
      form_search.click_button
````

I get this error:

> too many connection resets (due to end of file reached - EOFError) after 0 requests on 54261840, last used 1491919097.3684318 seconds ago

I am working with ruby 2.0.0 and mechanize 2.7.5

I try change the `keep_alive` to false, add an `idle_timeout`, this code: [http://scottwb.com/blog/2013/11/09/defeating-the-infamous-mechanize-too-many-connection-resets-bug/](http://scottwb.com/blog/2013/11/09/defeating-the-infamous-mechanize-too-many-connection-resets-bug/ ) but nothing work.

**Comment by flavorjones** [comment]
This seems likely to be an issue within `net-http-persistent`, as this error is emitted by that rubygem.
