### ISSUE TITLE
Incompatibility with JRuby

### ISSUE THREAD

**Issue by shideneyu** [sparklemotion/mechanize#463]
Contrarily to #209 , Mechanize is not compatible with JRuby.  Every Mechanize builds fail for JRuby on Travis.

https://travis-ci.org/sparklemotion/mechanize/jobs/91557462

I also got the same issue as Travis while using Mechanize on JRuby:

```
NoMethodError: undefined method `name' for nil:NilClass
```

**Comment by alkalinecoffee** [comment]
This appears to be resolved in 0e827f296ff29e6b35ed700a47694aea0a57a561

**Comment by TheKidCoder** [comment]
This is still an issue in the RG build. When will a new release be cut?
