### ISSUE TITLE
socks proxy support?

### ISSUE THREAD

**Issue by MatzFan** [sparklemotion/mechanize#464]
I see that Mechanize doesn't currently support this from [#422](https://github.com/sparklemotion/mechanize/issues/422). Does this mean you would not consider adding this feature - even via a PR? For example, I have successfully used the simple monkey-patch in [this Gist](https://gist.github.com/kuroineko/1854726). It does add a dependency on the [socksify](https://github.com/astro/socksify-ruby) gem, which you may not want of course.

**Comment by daidoji** [comment]
+1

**Comment by SorataAragaki** [comment]
+1

**Comment by Ekultek** [comment]
+1

**Comment by drbrain** [comment]
I don't think we want a hard dependency on the socksify gem. We could incorporate this as `require 'mechanize/socks_proxy'` that would raise an exception saying "install socksify" if it wasn't installed.

**Comment by MatzFan** [comment]
Eminently sensible solution - would you like a PR to implement this?

**Comment by weshatheleopard** [comment]
@drbrain: see https://github.com/sparklemotion/mechanize/pull/507

**Comment by flavorjones** [comment]
I'm open to merging this functionality treating `socksify` as an optional dependency. **However** the patch at #507 does not work with recent `net-http-persistent` versions (see #535). If someone wants to provide an updated patch I'll take a look.

**Comment by flavorjones** [comment]
Closing this issue, but I would accept a PR for this functionality if it can be made to work with recent versions of `net-http-persistent`.
