### ISSUE TITLE
Follow_meta_refresh only works on the second try on the same agent

### ISSUE THREAD

**Issue by chaner** [sparklemotion/mechanize#465]
Calling the get method twice seems to have different outcomes on the same agent. With the follow_meta_refresh flag set, it should return the result of the second call.

```
agent ||= Mechanize.new do |m|
  m.follow_meta_refresh = true
end

agent.get('http://hil.tn/X4V0Lc').uri.to_s #first time it goes to one of the redirect
agent.get('http://hil.tn/X4V0Lc').uri.to_s #second time it goes to the final destination, which is desired
```

**Comment by flavorjones** [comment]
@chaner Sorry for the delay in responding. With current versions of mechanize, I can't reproduce what you're describing. Please feel free to comment or open a new issue if you're still having issues, and would like to help me reproduce.
