### ISSUE TITLE
documentation for Mechanize::Agent#allowed_error_codes

### ISSUE THREAD

**Issue by cartoloupe** [sparklemotion/mechanize#472]
The [changelog](https://github.com/sparklemotion/mechanize/blob/master/CHANGELOG.rdoc#260) mentions addition of `Mechanize::Agent#allowed_error_codes`.

However, I was unable to locate this feature or its usage in the docs or guides.

How does one go about updating these [docs](http://docs.seattlerb.org/mechanize/)?

I am currently using this feature like this and it is working:

```
    @agent  = Mechanize.new do |mech|
      mech.agent.allowed_error_codes << 503
    end

```

**Comment by knu** [comment]
@drbrain @tenderlove What can we do to update the doc on docs.seattlerb.org in a timely manner?  It is currently so outdated.

**Comment by knu** [comment]
There is also mechanize.rubyforge.org, but as you know rubyforge will be shut down eventually.
Should we point to http://www.rubydoc.info/gems/mechanize/Mechanize for now?

**Comment by knu** [comment]
Aside from where to host our latest docs, I slightly improve rdoc for the attribute in b1fcc004.

**Comment by leejarvis** [comment]
> There is also mechanize.rubyforge.org, but as you know rubyforge will be shut down eventually.
Should we point to http://www.rubydoc.info/gems/mechanize/Mechanize for now?

I think so yes. I've change the GitHub Homepage URL and I think we can tweak the README too
