### ISSUE TITLE
Facebook Scraping issue

### ISSUE THREAD

**Issue by santosh-btc** [sparklemotion/mechanize#474]
agent = Mechanize.new

agent.get 'http://mediaserver-cont-ch1-2-v4v6.pandora.com/images/public/rovi/albumart/3/2/7/3/075679453723_500W_500H.jpg - work in local and give Mechanize::Page object.

agent.get 'http://mediaserver-cont-ch1-2-v4v6.pandora.com/images/public/rovi/albumart/3/2/7/3/075679453723_500W_500H.jpg - not working in production.gives Mechanize::Image object.

Please Help me. i am stuck here.

**Comment by knu** [comment]
Isn't it a JPEG image?  If so, I think it is your production environment where it is working correctly.  How does the Mechanize::Page object you obtain locally look like?  Is it a valid HTML document?  Chances are some edge servers of the CDN are responding with a broken copy of the content with the wrong content-type or something.

**Comment by leejarvis** [comment]
Going to close this until more feedback. Thanks
