### ISSUE TITLE
Hostname Mismatch and SNI

### ISSUE THREAD

**Issue by lukad03** [sparklemotion/mechanize#479]
I'm connecting to a server that uses SNI. As a result, I'm randomly seeing hostname mismatch errors. When connecting to the server using cURL/openssl with the hostname specified though, the correct certificate is always returned.

I know VERIFY_NONE works but that also introduces serious vulnerabilities that I'd like to avoid.

Is there a workaround for specifying the hostname as an argument for a new instance of Mechanize? I've posted a question on StackOverflow as well: http://stackoverflow.com/questions/38426727/mechanize-hostname-matching

**Comment by lukad03** [comment]
It looks like HTTP Persistent enables a way to pass in the hostname here: https://github.com/drbrain/net-http-persistent/blob/master/lib/net/http/persistent/ssl_reuse.rb So if Mechanize enabled a hostname attribute to be defined, in theory this would be resolved.

**Comment by knu** [comment]
What version of OpenSSL are you using?  It looks like `OpenSSL::SSL::SSLSocket#hostname=` is available if OpenSSL is configured with `--enable-tlsext`, which was added in OpenSSL 0.9.8f and made default in 0.9.8j.

**Comment by lukad03** [comment]
I'm using `OpenSSL 1.0.1f 6 Jan 2014`. Upon further investigation, I've found that the server I'm scraping has a self-signed root certificate in addition to it's other valid certificates . Would this cause intermittent failures @knu?

**Comment by knu** [comment]
I'm not sure as I have no idea what exactly is the error you are seeing.
In addition to some error backtrace, a code snippet for reproduction would really be nice.

**Comment by lukad03** [comment]
I don't have access to the error at the moment, but I know it included `hostname does not match the certificate` and it occurs intermittently.

Here's the code snippet:
```
agent = Mechanize.new
agent.user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.11 (KHTML, like Gecko) Chrome/23.0.1271.97 Safari/537.11"
agent.verify_mode = OpenSSL::SSL::VERIFY_PEER

page = agent.get "https://www.nslds.ed.gov/npas/index.htm"
```
Using `ruby "2.2.3"` with `gem "mechanize", ">= 2.7.4"`

**Comment by flavorjones** [comment]
Unfortunately this site no longer exists, so I'm still having trouble reproducing this. I'm going to close because of the age of this issue, but feel free to comment or open a new issue if you can help us reproduce.
