### ISSUE TITLE
Mechanize::File lacks #content_type()

### ISSUE THREAD

**Issue by hadmut** [sparklemotion/mechanize#481]
Hi, 

I am currently using mechanize to access a web site which allows to query several files (.csv, .pdf, .xml,...) through a form. Works well with mechanize, after filling and submitting the form I get a Mechanize::File object as expected. 

Unfortunately the Mechanize::File does not tell the content-type, it does not have a content_type() function. Since inspecting the content is poor style, it would be nice to get the conent-type the web server has given with the object in the response header. 

regards

**Comment by skippyPeanutButter** [comment]
Hey @hadmut, couldn't you just access the content-type from a Mechanize::File object with the `[]` method?

For example

```
require 'mechanize'

mech = Mechanize.new
url = 'http://www.sample-videos.com/csv/Sample-Spreadsheet-10-rows.csv'
file = mech.get(url) # => Mechanize::File

file['content-type'] # => "text/csv"

```
