### ISSUE TITLE
Mechanize: search in page body force an encoding exception

### ISSUE THREAD

**Issue by petRUShka** [sparklemotion/mechanize#489]
I have following pretty simple code

```
require 'rubygems'
require 'mechanize'

URL = 'http://yandex.ru'

agent = Mechanize.new
page = agent.get(URL)

# page.encoding => UTF-8
# page.body.encoding => ASCII-8BIT

page.body.include?("Карты") # cyrillic
```

And on the last line of that code ruby yield an error:

```
in `include?': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)
```

I consider that behavior as a bug.

Solutions [from that question][1] don't help.

  [1]: http://stackoverflow.com/questions/8864493/how-to-get-mechanize-to-auto-convert-body-to-utf8

**Comment by leejarvis** [comment]
You're comparing the page encoding with a different encoding. Try forcing your encoding first:

```
page.body.include?("Карты".force_encoding("ascii-8bit")) #=> true
```
