### ISSUE TITLE
Is there any way can stub HTTP request in mechanize?

### ISSUE THREAD

**Issue by tsaohucn** [sparklemotion/mechanize#490]
I use webmock to stub HTTP request in mechanize, but it looks like incompatible, is there any way can stub HTTP request in mechanize?

**Comment by kinopyo** [comment]
@tsaohucn Any chance you were missing a header when stubbing with webmock? 🙂 The example below is compatible with mechanize.

```ruby
stub_request(:get, "http://example.com").to_return(
  status: 200,
  body: "<title>The Title</title>...",
  headers: { "Content-Type" => "text/html" }
)
```
