### ISSUE TITLE
page.title gives unexpected results on pages with multiple <title> tags

### ISSUE THREAD

**Issue by nivshah** [sparklemotion/mechanize#493]
I want to pull the title of a user-provided URL. When I use `page.title`, on some pages that have multiple <title> tags (possible reasons: SVGs with <title> tags, other metadata inserted downpage) I get a concatenation of title strings that aren't the expected contents of the <title> tag inside <head>.

I am currently using `page.at('head title').text.strip` to get the page's title consistently. Does it make sense to change the behavior of `page.title` to only take the title from the page's head? Or is there a reason `page.title` works the way it currently works?

Thanks for all the hard work. This gem is really great.

**Comment by knu** [comment]
This has been fixed by #503.
