### ISSUE TITLE
Replace unmaintained HTTP NTLM library with RubyNTLM

### ISSUE THREAD

**Issue by sempervictus** [sparklemotion/mechanize#495]
The HTTP NTLM library appears dead - almost 10y since an update. RubyNTLM is actually conflicting with the old gem in bundles which end up with both as dependencies when Mechanize is a dependency itself.

**Comment by cielavenir** [comment]
https://github.com/sparklemotion/mechanize/issues/436

**Comment by deivid-rodriguez** [comment]
Seems related: https://github.com/pyu10055/ntlm-http/pull/13

**Comment by sempervictus** [comment]
Wow, this is still open...
Pretty sure I've literally reverse engineered ssp3 signing since this was opened. If marking this as a security issue helps move it along, it _is_ one since the lib in use is leveraging old and easy to intercept/reuse ntlm message formats.
