### ISSUE TITLE
bug when getting special #id (specials caracters)

### ISSUE THREAD

**Issue by Argorate** [sparklemotion/mechanize#497]
I use wikipedia to get definitions and some informations on words.

if you get this source : view-source:https://fr.wiktionary.org/wiki/dessin

you will see `<span class="mw-headline" id=".C3.89tymologie">`

but if I try : `page.search('#C3.89tymologie')` or `page.search('.mw-headline[id=".C3.89tymologie"]')` it doesn't works. The first example raise an error :  `Nokogiri::CSS::SyntaxError 

unexpected '#' after '' `, the second return empty string

So can you fix this special case? I think you just don't think about it.

thx.

**Comment by rnitta** [comment]
It is not mechanize's fault.
It is the specification of Nokogiri.

and you can search such elements like below
```
page.search('#\.C3\.89tymologie')
```

escape `.` -> `\.`
