### ISSUE TITLE
Please add new maintainers

### ISSUE THREAD

**Issue by brauliobo** [sparklemotion/mechanize#504]
Hi, there is quite a number of PRs, ruby and nokogiri updates to be done and the current team isn't able to continue with the work. Maybe there are people out there that could help. I could contribute with some basic tasks if anyone with more time can't.

**Comment by weshatheleopard** [comment]
I can possibly help.

**Comment by leejarvis** [comment]
Thanks and sorry for the absence. I'm happy to add more maintainers. 

I realise I have really not had time for Mechanize for a long while now, so I'm open to discussing collaboration for anyone interested. However, I don't agree that there are a lot of PRs open, so I think this will require much more than just somebody who can merge already prepared pull requests. My suggestion, if you're interested, would be to pick a task from the list of issues and submit a PR so we can discuss adding contributors.

Hope to see some incoming PRs!
