### ISSUE TITLE
How to upgrade re. security vulnerability for nokogiri < 1.8.1

### ISSUE THREAD

**Issue by jayqui** [sparklemotion/mechanize#514]
I have a small project whose Gemfile lists `gem "mechanize", "~> 2.7"`.

GitHub is telling me that
> The `nokogiri` dependency defined in `Gemfile.lock` has a known critical severity security vulnerability in version range < `1.8.1` and should be updated.

My `Gemfile.lock` includes

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    ...
    mechanize (2.7.5)
      domain_name (~> 0.5, >= 0.5.1)
      http-cookie (~> 1.0)
      mime-types (>= 1.17.2)
      net-http-digest_auth (~> 1.1, >= 1.1.1)
      net-http-persistent (~> 2.5, >= 2.5.2)
      nokogiri (~> 1.6)
      ntlm-http (~> 0.1, >= 0.1.1)
      webrobots (>= 0.0.9, < 0.2)
    ...
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    ...
```

What version of `mechanize` should I specify to update my dependency on `nokogiri` to > `1.8.1`?

**Comment by guillaumebihet** [comment]
I think you should just run "bundle update", that solved the issue for me.

**Comment by MatzFan** [comment]
Latest release of Mechanize (2.7.5) specifies Nokogiri "~> 1.6" in the gemspec and is therefore potentially vulnerable. I just added this line to my Gemfile to ensure my project uses 1.8.1 or greater.
`gem 'nokogiri', '~> 1.8.1'`

**Comment by IDoRemember** [comment]
nokogiri (>= 1.8.1)     

run “gem start”

**Comment by flavorjones** [comment]
I believe the information in this issue is sufficent to resolve the original question, so I'm closing. Please comment if there is still an issue.

**Comment by RylanSchaeffer** [comment]
`bundle update` does not work for me. What is an alternative solution?

**Comment by RylanSchaeffer** [comment]
`gem start` yields the error:

`ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command start`
