### ISSUE TITLE
Generate a new version

### ISSUE THREAD

**Issue by perezgb** [sparklemotion/mechanize#519]
Hey folks,

it seems like this gem hasn't had a new version since 2016 but there were a lot of changes since then. Any way we can get a new version released? Anything I can do to help with that?

Thanks!

**Comment by luislavena** [comment]
@knu will be possible for you to generate a new release of Mechanize? It's been a while since last version and under some scenarios I cannot deploy/use the git version.

Thank you.

**Comment by knu** [comment]
Just released! https://rubygems.org/gems/mechanize/versions/2.7.6

**Comment by luislavena** [comment]
Thank you @knu!!! ❤️ ❤️ ❤️
