### ISSUE TITLE
ensuring mechanize uses TLS 1.1

### ISSUE THREAD

**Issue by tansaku** [sparklemotion/mechanize#520]
We're trying to work out how to ensure that mechanize uses TLS 1.1 and above.

There's a mention of setting the user agent in https://github.com/sparklemotion/mechanize/issues/123#issuecomment-24431143

> `ruby -rmechanize -e 'm = Mechanize.new; m.agent.ssl_version = :TLSv1; m.get "https://blah"'`

Does anyone know if this is the right way to ensure mechanize is on a particular version of TLS? or is there some particular gem dependency that should be set?

Many thanks in advance

**Comment by leejarvis** [comment]
Yes. The SSL version is passed through to [net-http-persistent](https://github.com/drbrain/net-http-persistent) and thus net/http + openssl. See documentation for [Net::HTTP](https://ruby-doc.org/stdlib-2.5.3/libdoc/net/http/rdoc/Net/HTTP.html) (search for `ssl`)
