### ISSUE TITLE
Errno::EMFILE Too many files open?

### ISSUE THREAD

**Issue by maxiedaniels** [sparklemotion/mechanize#521]
I'm using a twenty thread pool to scrape website pages using Mechanize, but I'm getting this error for some reason. There's nothing crazy about my code.. it's basically:

```
my_thread_pool.process {
    agent = Mechanize.new
    page = agent.get("someurlhere")
    <doing something simple with page.html>
}
```

It's saying stuff about `/var/folders/jn/1bwvnjc145jdtjjlcd76g_fw0000gn/T/mechanize-gunzip20180416-49164-y8d24t>` which seems to be a temp folder of some sort... is there a reason I'd be hitting my system's max open files with only twenty threads of Mechanize??

**Comment by lucianoshl** [comment]
+1

**Comment by flavorjones** [comment]
@maxiedaniels I'm having trouble reproducing this issue on my local dev environment using Mechanize 2.7.7. Here's the script I'm running:

```ruby
#!/usr/bin/env ruby

require "bundler/inline"

gemfile(true) do
  gem "mechanize"
  gem "concurrent-ruby"
end

pool = Concurrent::FixedThreadPool.new(20)

10_000.times do
  pool.post do
    putc ">"
    agent = Mechanize.new
    page = agent.get("http://localhost:8000")
    putc "<"
  end
end

pool.shutdown
pool.wait_for_termination
```

Is there additional context you can provide to help me reproduce this?

**Comment by flavorjones** [comment]
(Side note: the server I'm hitting locally supports gzip-encoded responses)
