### ISSUE TITLE
Inifinite loop on invalid meta redirect

### ISSUE THREAD

**Issue by rusikf** [sparklemotion/mechanize#523]
Hello, in this case ( it is not W3C correct china site) there is infinite loop( meta redirect to self, but mechanize dont recognize it)
```ruby
agent = Machanize.new
agent.follow_meta_refresh = true
agent.get(''http://www.mtn.co.kr")
```
So i disabled meta redirect, and redirect manually once. Is it possible to setup `meta_redirects_limits` ? Thanks

**Comment by flavorjones** [comment]
The issue here appears to be that site responding with this header:

```
 <meta http-equiv="refresh" content="200;url=/index.mtn" />
```

which indicates a 200-second delay. So this is not an infinite loop (Mechanize Agent by default will limit redirects at 20), but merely a really long delay on the part of the website.
