### ISSUE TITLE
Getting a process not implemented error after updating to 2.7.6

### ISSUE THREAD

**Issue by krishnakb** [sparklemotion/mechanize#525]
We are seeing this error for 2.7.6. Works on 2.7.5

Process#getrlimit not yet implemented (NotImplementedError)
org/jruby/RubyProcess.java:959:in `getrlimit'

**Comment by leejarvis** [comment]
Please can you re-open this issue with a full stack trace on [net-http-persistent](https://github.com/drbrain/net-http-persistent), which is where the error originates? Thanks!
