### ISSUE TITLE
ConnectionPool::PoolShuttingDownError

### ISSUE THREAD

**Issue by pugsiman** [sparklemotion/mechanize#527]
Since the last release, I receive lots of `ConnectionPool::PoolShuttingDownError` exceptions with the message "no connections are checked out". I've isolated it to the net-http-persistent upgrade to version 3. As that release is several years old in itself, I assume something has broken in mechanize itself.

**Comment by brauliobo** [comment]
Also related to `net-http-persistent` 3.0, see https://github.com/sparklemotion/mechanize/issues/528

**Comment by brauliobo** [comment]
I'm getting lots of this error with version 4.0.1

**Comment by flavorjones** [comment]
@brauliobo Please open a new issue, and include as much information as you can to help us reproduce it, including versions of Mechanize and dependencies. Thank you!
