### ISSUE TITLE
undefined method `implementation' for HTTP::CookieJar::AbstractStore:Class

### ISSUE THREAD

**Issue by jakemack** [sparklemotion/mechanize#530]
Hi, I get this error randomly when using Mechanize with Sidekiq. It is likely an autoloading issue as mentioned here: https://github.com/sparklemotion/http-cookie/issues/6. Any chance anyone here has found a workaround or fix for this?

**Comment by leejarvis** [comment]
Yes, this is related to `HTTP::CookieJar` I'm afraid. I'm going to close this but open to feedback if anyone can reproduce (please comment on the above issue on http-cookie rather than this one)
