### ISSUE TITLE
How to use Mechanize with the site use AngularJS or ReactJS

### ISSUE THREAD

**Issue by honeypc** [sparklemotion/mechanize#540]
I'm trying to use `Mechanize` to get the content the page render via `AngularJS` but I can't get the content of that site. I also find the way to do that but nothing. Anyone had any solution for that, help me. Thanks so much

**Comment by barbolo** [comment]
It'll be easier to interact with that website using https://github.com/GoogleChrome/puppeteer.

Mechanize doesn't run `JavaScript` code and doesn't render web pages. You should write the `AngularJS`/`JavaScript` behaviour in Ruby if you want to mimic its behaviour.

You should start by checking the network communication tab in your browser's developer tools and that may bring you some ideas on how to automate the website.

**Comment by leejarvis** [comment]
Closing as per the comment from Rafael
