### ISSUE TITLE
Downloading a really large file

### ISSUE THREAD

**Issue by kapso** [sparklemotion/mechanize#549]
I need to download (and upload to S3) a really large file (1.5 GB). I need to run this on a serverless environment so I may not necessarily have access to a local disk. How can I do this with mechanize? Thanks.

I just tried the following code and this code is still running for last 30 minutes.

```ruby
agent.pluggable_parser.default = Mechanize::Download
agent.get(url).body
```

**Comment by flavorjones** [comment]
Hi @kapso, sorry for the slow response. Using `Mechanize::Download#body` is documented as "this may use lots of memory if the response body is large", so probably not what you want to do.

You can access the parser's underlying `IO` object via the `#body_io` attribute; you may want to try reading a chunk at a time and writing those chunks to your destination.
