### ISSUE TITLE
HTTP2 required by Cloudfare Bot checks

### ISSUE THREAD

**Issue by brauliobo** [sparklemotion/mechanize#555]
Hi, this page for instance https://www.thuisbezorgd.nl/en/new-york-pizza-de-bilt uses the Cloudflare bot protection that check for the HTTP2 protocol usage. If HTTP1 is used then it blocks access and redirect to a browser check.

How can use HTTP2 with Mechanize? Is there any support or plans already?

**Comment by mikerodrigues** [comment]
HTTP2 works fine for me with mechanize.

**Comment by flavorjones** [comment]
@brauliobo When I run this script, I'm unable to reproduce what you're describing:

```ruby
#! /usr/bin/env ruby

require 'mechanize'

agent = Mechanize.new
agent.log = Logger.new($stderr)
agent.get("https://www.thuisbezorgd.nl/en/new-york-pizza-de-bilt")
puts agent.page.body
```

I'm going to close this as "stale", but if you'd like to continue the conversation please feel free to reply and we can reopen it. Thanks!
