### ISSUE TITLE
Serialize Mechanize::Page to YAML & deserialize

### ISSUE THREAD

**Issue by benjaminelkrieff** [sparklemotion/mechanize#577]
Hello.

We are trying to implement a mechanism that looks like VCR and the cassette implementation.

We have a web page loading into a Mechanize::Page object and we dump it into a YAML file.

When we choose to use the cassette, we want to read the yaml file and rebuild the Mechanize::Page instance by using the initializer and giving the 5 following parameters: uri - response - body - code - mech

The problem is that when we try to deserialize the yaml file into a hash we get the following error:
TypeError Exception: allocator undefined for Proc

We identified that the two problematic lines are inside the mech param.

So we tried not using the mech param but then we don't get a Mechanize::Page anymore.

Is there a better way to Serialize / Deserialize a Mechanize::Page object ?

**Comment by flavorjones** [comment]
Hi @benjaminelkrieff, I'll try to help.

In the interest of helping you solve your problem, can you tell me a bit more about what you're trying to do? Mechanize has a few different capabilities when it comes to writing files to local disk. I'd like to avoid the [XY Problem](https://en.wikipedia.org/wiki/XY_problem) where we work on `Proc` serialization but don't actually solve your problem.

Maybe to start off: have you tried saving the page's body as html, and reading that back off disk? Like this:

```ruby
#!/usr/bin/env ruby

require 'mechanize'

# read the document off the internet
mechanize = Mechanize.new
page = mechanize.get("http://nokogiri.org")

# save to a local file
page.save_as("foo.html")

# read back in from the local file
uri_to_file = URI::File.build(path: File.expand_path("foo.html")) # => "file:///home/flavorjones/code/oss/mechanize/foo.html"
loaded_page = mechanize.get(uri_to_file)

# it's a real Mechanize::Page
puts loaded_page.body
```

**Comment by benjaminelkrieff** [comment]
Hello and thanks for your answer.
I tried your code and Mechanize.get truncates the "html" part of the file so it throws a Net::HTTPNotFound error

**Comment by flavorjones** [comment]
@benjaminelkrieff Can you please provide a bit more information, so that I can reproduce what you're seeing?

**Comment by benjaminelkrieff** [comment]
Yes sure:

What we are trying to do is implementing a VCR-like system. When we chose to use a cassette and not download the page again, if it's the first time, we save the page in a file. When it's not the first time, we want to read the page from the file and reconstruct a Mechanize::Page object. This is crucial for the integrity of our code. 

Unfortunately, Mechanize::Page comes with it's own attributes like mech, and can be serialized to YAML but not deserialize from YAML because of the 'Proc' attribute. We are trying to find solutions to this but we're having a hard time.

We managed to reconstruct a Nokogiri::HTML::Document but for the integrity of our code we prefer not to use that solution.

Unless there is a way to convert a Nokogiri::HTML::Document to a Mechanize::Page, it seems that we are stuck on a problem that shouldn't even exist.

**Comment by flavorjones** [comment]
@benjaminelkrieff I provided you code above that reads HTML from disk and creates a Mechanize::Page.

**Comment by benjaminelkrieff** [comment]
I tried the code and it didn't work

**Comment by flavorjones** [comment]
@benjaminelkrieff ... Yes, and I asked "Can you please provide a bit more information, so that I can reproduce what you're seeing?"

**Comment by flavorjones** [comment]
For the record, my environment is:

- Mechanize 2.7.7
- Nokogiri 1.11.3
- ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]

**Comment by benjaminelkrieff** [comment]
Thank you I will give it a shot!

**Comment by flavorjones** [comment]
Closing, but if you're still having problems feel free to comment and we can continue the chat!
