### ISSUE TITLE
Improve `#download` to be supported also post method

### ISSUE THREAD

**Issue by KSH-code** [sparklemotion/mechanize#583]
When file downloads with form, its method is post usually .
so `#download` which supports post method would be nice in my opinion.

it could be?

**Comment by flavorjones** [comment]
@KSH-code thank you for asking this question!

I would like to understand more deeply how you would like Mechanize to work. Are you doing a `POST` with query parameters using `Mechanize#post`, or are you filling out a form and calling `Form#submit`?

**Comment by KSH-code** [comment]
@flavorjones 
I'm using only `Mechanize#post` for download file to request service providers' endpoint.
because `Mechanize#downlaod` does not support method with post so I am now using `Mechanize#post` and `pluggable_parser.default = Mechanize::Download`.

and then access direct `#page.body_io`.

query parameter is not used!

What I want is just call only `#download` and then access page object.
