### ISSUE TITLE
>"bug.svg" file.

### ISSUE THREAD

**Issue by joshuamitchem** [sparklemotion/mechanize#593]
> I can't reproduce what you're seeing at the moment without a version,https://git

BTW, any idea how can I modify `svg_merged = Nokogiri::XML(text, &:noblanks)` to enable both `noblanks` and `huge`?

_Originally posted by @matkoniecz in https://github.com/sparklemotion/nokogiri/issues/2201#issuecomment-791743186_

**Comment by flavorjones** [comment]
Answered in https://github.com/sparklemotion/nokogiri/issues/2201#issuecomment-791759761
