### ISSUE TITLE
when down loading should start with https//sparkle motion/joshuamitchem mechanize

### ISSUE THREAD

**Issue by joshuamitchem** [sparklemotion/mechanize#594]
if u start with that should be able to download without having any problems

**Comment by joshuamitchem** [comment]
-ll

**Comment by joshuamitchem** [comment]
@joshuamitchem can and will download @sparklemotion.com

**Comment by flavorjones** [comment]
@joshuamitchem I don't understand. Can I ask you to please state clearly what problem you're having and how I can reproduce it?
