### ISSUE TITLE
Compatibility Inquiry: mechanize 2.10.0 with Ruby 3.3.0

### ISSUE THREAD

**Issue by sydverisk** [sparklemotion/mechanize#635]
Hi,

I'm seeking confirmation regarding the compatibility of the mechanize 2.10.0 gem with the recently released Ruby 3.3.0 (December 25, 2023).

While I reviewed the gem's documentation on RubyGems https://rubygems.org/gems/mechanize/versions/2.10.0, it only specifies a minimum required Ruby version of 2.6. Unfortunately, I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0.

Given your expertise in this area, could you offer any insights or leads on this matter? Any information you can provide would be greatly appreciated.

Thank you for your time and assistance!

**Comment by flavorjones** [comment]
@sydverisk Hello. When you say "I haven't found any explicit confirmation on compatibility with newer versions like 3.3.0" can you help me understand where you are looking, and what you are looking for?

**Comment by sydverisk** [comment]
Hi @flavorjones 
Thanks for the reply, I am looking to update my ruby version with the latest stable 3.3.0. I use the gem mechanize 2.7.7 in my current environment ruby 2.5.0p0. So I want to know if the gem mechanize 2.7.7 or 2.10.0 is compatible with the current stable ruby 3.3.0?
The resources I went through are 
https://rubygems.org/gems/mechanize/versions/2.10.0
https://github.com/sparklemotion/mechanize
https://www.rubydoc.info/gems/mechanize/

Thanks in advcance!

**Comment by flavorjones** [comment]
Mechanize v2.9.2 and later (including v2.10.0) are tested against Ruby 3.3 and definitely support it. Earlier versions of Mechanize _very likely_ run fine under Ruby 3.3.

The changelog should have specified this, but I think we've gotten out of practice saying "new version is supported" when tests are green and no action was needed to work with the new version of Ruby.

I hope this helps!

**Comment by sydverisk** [comment]
Thanks @flavorjones for the response, I appreciate it!
