### ISSUE TITLE
Feature Request: Handle responses that require Brotli compression

### ISSUE THREAD

**Issue by weshatheleopard** [sparklemotion/mechanize#649]
I have encountered a webserver that ignores `Accept-Encoding:` header and still returns the content the way it wants. As a result, I get `unsupported content-encoding: br ` error from Mechanize.

I was able to circumvent that with the followng code (using [Brotli gem](https://github.com/miyucy/brotli)):
```
gem 'brotli'

a = Mechanize.new { |agent|
  agent.content_encoding_hooks << lambda do |_a, _uri, response, body_io|
    case response['Content-Encoding'].to_s
    when 'br' then
      response['Content-Encoding'] = 'none'
      body_io.string = Brotli.inflate(body_io.read)
    end
  end
}
a.get "https://the.problematic/url".
```
I started making a PR (expanding `case` statement in `response_content_encoding` in `lib/mechanize/http/agent.rb`) but then realized that there are multiple intricacies that the author himself has a way better knowledge of, so I think I should better allow him to handle that using the above code snippet as a guide rather then forcing him to redo my scribblings from scratch, anyway. (Being an author of a gem myself, I barely ever accept incoming PRs unmodified).

**Comment by flavorjones** [comment]
@weshatheleopard Thanks for reporting this, and for suggesting this approach to handle these kinds of responses.

If you don't want to submit a PR with the fix, I would welcome a PR that introduces a failing test. I'd be starting from scratch on trying to reproduce what you're seeing without one, and that's just enough friction to prevent me from prioritizing this anytime soon.

**Comment by flavorjones** [comment]
For whatever it's worth, the solution should be as straightforward as:

- add to the case statement in `response_content_encoding`
- calling a new method, `content_encoding_brotli`, which follows the existing patterns for `inflate` and `gunzip`, taking care not to handle errors and handle IO object state

I can do it, but I don't think it's more complicated than that.

**Comment by weshatheleopard** [comment]
@flavorjones I can certainly make an attempt at PR, but I'm warning you it will be very simplistic comparing to the infrastructure that you already have in the gem, and you will have to heavily modify my PR anyway. 
And yes, that's what I was planning to do — but then I realized that that method generates `auto_io` which additionally handles tempfiles and read chunking, and that's over my head (in application to `Mechanize` of course, I can handle that `genericly` but I don't know the details on how Mechanize deals witht them).
