### ISSUE TITLE
Possible to force HTTP/1.1?

### ISSUE THREAD

**Issue by FinnLawrence** [sparklemotion/mechanize#657]
I'm working with an old site that seems to have no support at all for HTTP/2 and depending on the client, either hangs or closes the connection when the client attempts to negotiate the ALPN handshake to assess HTTP/2 support.

I unfortunately can't change anything on the server/site. If I make the requests with a library that supports hard-coding HTTP/1.1 (e.g. Typhoeus) then it works fine.

I've searched around but couldn't find an answer - is it possible to hard code/force this when using Mechanize?

**Comment by flavorjones** [comment]
@FinnLawrence Mechanize uses net-http-persistent to manage HTTP connections. To my knowledge, net-http-persistent doesn't support HTTP/2, but maybe I'm wrong.

All of which is to say: without more information I can't help diagnose what's going on. Can you share your logs from the mechanize agent? You can generate verbose logs to stdout with:

```ruby
agent.log = Logger.new $stdout
```

or you can pass any IO object there if you want to write to file. This would help me understand what's going on and maybe I can suggest a workaround.
